name: MobStatusChange
version: @version@
main: com.github.secretx33.mobstatuschange.MobStatusChange
api-version: 1.16
authors: [SecretX]
description: This plugin allows quick modification to mob status and damage, as well as allowing poison to kill.
website: https://github.com/SecretX33

commands:
  msc:
    description: MobStatusChange
    usage: /<command>
    aliases: mobstatuschange

permissions:

  msc.*:
    description: Gives access to all @name@ commands
    children:
      msc.reload: true
      msc.debug: true

  msc.reload:
    description: Allows you to reload the plugin config
    default: op
